### ISSUE TITLE
installation failed on a newly installed raspberry pi

### ISSUE THREAD

**Issue by jdrouet** [virtualabs/btlejack#19]
I just reinstalled a raspberry pi with the last raspbian. I installed `python3` and `python3-pip`.
And when I run `sudo pip3 install btlejack` I get this error:

```
Collecting btlejack
  Using cached https://files.pythonhosted.org/packages/1a/5b/e4cb52e4182d7992c292944f0ee1a1e4a0eeac56aaae122cbcd3ee4e20a0/btlejack-1.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ed74slxh/btlejack/setup.py", line 26, in <module>
        long_description = read('README.rst'),
      File "/tmp/pip-build-ed74slxh/btlejack/setup.py", line 9, in read
        return open(os.path.join(os.path.dirname(__file__), fname)).read()
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2922: ordinal not in range(128)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ed74slxh/btlejack/
```

**Comment by floyd-fuh** [comment]
see https://github.com/virtualabs/btlejack/issues/13

Try to execute this before running that command:

```
export LC_CTYPE=utf-8
export PYTHONIOENCODING=utf-8
```
