### ISSUE TITLE
Junk when running discover

### ISSUE THREAD

**Issue by wxor** [virtualabs/btlejack#48]
Having a problem when running discover after a hijack. "@> b'SP'" looks to be echoed back on to the cli and after about 30secs there is a "L2CAPException". It also takes a few attempts to hijack. Thanks in advance, love your work. Your DEFCON26 talk was awesome :)

BtleJack version 1.3

[i] Using cached parameters (created on 2019-08-05 20:50:20)
[i] Detected sniffers:
 > Sniffer #0: fw version 1.3

[i] Synchronizing with connection 0xaf9a9b29 ...
✓ CRCInit: 0xe85837
✓ Channel map is provided: 0x1ffffff800
\ Computing hop interval@> b'Recovering hop interval ...'
✓ Hop interval = 39
✓ Hop increment = 13
[i] Synchronized, hijacking in progress ...
[i] Connection successfully hijacked, it is all yours \o/
btlejack> discover
btlejack> @> b'SP'
Traceback (most recent call last):
  File "/usr/local/bin/btlejack", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/btlejack/__init__.py", line 329, in main
    supervisor.process_packets()
  File "/usr/local/lib/python3.7/dist-packages/btlejack/supervisors.py", line 38, in process_packets
    self.on_packet_received(pkt)
  File "/usr/local/lib/python3.7/dist-packages/btlejack/ui.py", line 610, in on_packet_received
    super().on_packet_received(packet)
  File "/usr/local/lib/python3.7/dist-packages/btlejack/supervisors.py", line 307, in on_packet_received
    self.on_ll_packet(packet)
  File "/usr/local/lib/python3.7/dist-packages/btlejack/ui.py", line 575, in on_ll_packet
    self._pt.on_ll_packet(packet)
  File "/usr/local/lib/python3.7/dist-packages/btlejack/ui.py", line 273, in on_ll_packet
    response = L2CAP.from_bytes(packet.data[12:]).payload.payload
  File "/usr/local/lib/python3.7/dist-packages/btlejack/dissect/l2cap.py", line 35, in from_bytes
    raise L2CAPException()
btlejack.dissect.l2cap.L2CAPException

**Comment by virtualabs** [comment]
Fixed in version 2.0 (tag v2.0.0), not yet available in pip.
